version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-adbudget}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./backend/app/.env   # ← only at runtime
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app            # dev hot-reload
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  db_data:
